### ISSUE TITLE
Auto website update after push to master branch

### ISSUE THREAD

**Issue by Croydon** [inexor-game/services#1]
The server should get the latest version of the website automatically when somebody is pushing commits to the master branch.

Thanks :)

**Comment by Fohlen** [comment]
Agreed.

**Comment by Fohlen** [comment]
This should be done as following:
- git clones the CI master
- the application folder get's stripped
- community/project-site get's pulled
- finally the configuration is rebuilt

**Comment by Fohlen** [comment]
This is done in inexor-game/blog#3
