### ISSUE TITLE
Offer some delivery site similliar to cefbuilds.com

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/services#11]
What about using some frontend page to offer nightly builds? The plain FTP folder looks a little scary for everybody outside the project though..
cefbuilds.com is a great example imho..

**Comment by Croydon** [comment]
If you know how to do something like that with the Adrive APIs then just go for it :+1:

**Comment by Fohlen** [comment]
This issue was moved to inexor-game/code#258
