### ISSUE TITLE
Use wosign temporarily (instead of StartSSL)

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/services#4]
We could use wosign [(read the Golemn article)](http://www.golem.de/news/wosign-kostenlose-tls-zertifikate-aus-china-1502-112203.html) instead of StartSSL until let's encrypt is working propperly..
This would allow us to offer ALL of our services with SSL.

**Comment by Croydon** [comment]
I'm not sure if this is worth it for the few months till Let's Encrypt is ready. Our website isn't even ready yet and a stable release will still take some time, so we don't have much traffic anytime soon anyway.

**Comment by Fohlen** [comment]
Agreed,
