### ISSUE TITLE
Etherpad

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/services#5]
Once we managed to set up a node.js infrastructure for our servers we should consider to install [Etherpad](http://etherpad.org/) on top of it, to outsource from titan/piratenpad.

**Comment by koraa** [comment]
do you mean like the inexor game server using node.js?

**Comment by Fohlen** [comment]
Yes.

**Comment by koraa** [comment]
Well, just install node.js?

**Comment by Croydon** [comment]
Well done @Fohlen :)
