### ISSUE TITLE
Make clean-nightly.py working

### ISSUE THREAD

**Issue by Croydon** [inexor-game/services#6]
Currently our nightly builds don't get cleaned automatically after a specific time, so our server is regulary running out if disk space. We need to fix this.

**Comment by Fohlen** [comment]
This issue is going to be solved by outsourcing nightly.inexor.org to an external provider (mount Google drive as a backend)

**Comment by Croydon** [comment]
Even if we have more space by outsourcing, we still need a script which automatically deletes the old nightlies and ofc we should be able do directly upload new files via travis. Is that possible with e.g. Google Drive?

**Comment by Fohlen** [comment]
Yes it is. Google drive can be set-up to automatically do this.

**Comment by Fohlen** [comment]
We now have an external provider with 100GB space and it'd be enough to clean up files older than 1 month. Can be closed.
