### ISSUE TITLE
Adopt Open Code of Conduct

### ISSUE THREAD

**Issue by Croydon** [inexor-game/services#8]
I would like to adopt the Open Code of Conduct for the whole Inexor project as basic community/project guideline and a how-to-behave.

http://todogroup.org/opencodeofconduct/
https://github.com/todogroup/opencodeofconduct

Any contra concerns?

**Comment by Fohlen** [comment]
:+1:

**Comment by Fohlen** [comment]
Can you add this to https://community.inexor.org (maybe add a custom TOS page) ?

**Comment by Croydon** [comment]
Added to our wiki. https://github.com/inexor-game/data/wiki/Code-of-Conduct
Feedback is welcome :)

**Comment by Fohlen** [comment]
:+1: 
Nicely done!
