### ISSUE TITLE
Setup again demo page for UI concepts

### ISSUE THREAD

**Issue by Croydon** [inexor-game/services#9]
https://github.com/inexor-game/ui-prototype
=> http://inexor-game.github.io/ui-prototype/

The demo page should automatically fetch new pushes. Such a demo page is the easiest way to keep track of all UI suggestions and to quickly give them a look.

**Comment by Croydon** [comment]
I tagged bug because we already had such a thing once :D

**Comment by Fohlen** [comment]
It was set-up and ran by @sanitizer

**Comment by Croydon** [comment]
I know, but was still part of Inexor. Anyway, the label isn't that important :)

**Comment by Fohlen** [comment]
I don't know if this is really a necessary service ...  neither did I hear of anyone using it...?

**Comment by Fohlen** [comment]
This has been solved using github pages by @Croydon

**Comment by Croydon** [comment]
=> http://inexor-game.github.io/ui-prototype/
